server:
  port: 8003
spring:
  application:
    name: cloud-payment-service
  datasource:
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.spirngcloud.entities

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002:7002/eureka,http://eureka7001:7001/eureka