server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true
      datasource:  # 流控规则持久化 Nacos
        flow-datasource:
          nacos:
            server-addr: localhost:8848
            dataId: cloud-alibaba-sentinel-service  # ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        degrade-data-source: # 降级规则
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules # ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启 sentinel 对 feign 的支持
feign:
  sentinel:
    enabled: true
