server:
  port: 8002
spring:
  application:
    name: cloud-consumer-service
  datasource:
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.spirngcloud.entities
