server:
  port: 9527
spring:
  application:
    name: cloud-getway9527
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh            # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   # 匹配后提供服务的路由地址
          uri: lb://cloud-alibaba-sentinel-service
          predicates:
            - Path=/test**     # 断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
      # 跨域处理
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - DELETE
              - PUT
              - POST
    sentinel:
      transport:
        dashboard: localhost:8080